name: dynamicrafter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.4
  - av
  - "mkl<2025"
  - "intel-openmp<2025"
  - "setuptools<81"
  - pip
  - pip:
      - -r requirements-dynamicrafter.txt

