name: dust3r
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.4
  - pip
  - pip:
      - -r dust3r/requirements.txt
      - -r requirements-project.txt

